### ISSUE TITLE
Enhancing the tutorial video

### ISSUE THREAD

**Issue by wddler** [demkoen/DIH2-Phase3#11]
Dear Koen @kaaskopkoen ,

Can you please add a couple of things to make the tutorial video better? (demos/2021-11-09 20-48-19.mkv)
Such as:

- [x] Intro
- [x] Comment for each step: voiceover and/or subtitles
- [x] Maybe some conclusion

Thanks!

Denis Zatyagov

**Comment by wddler** [comment]
All done in the new video. Thanks!

**Comment by demkoen** [comment]
Denis,

I've made a new video, but I'm not completely satisfied with the result. I've underestimated the skill required for storytelling and forming coherent sentences while doing things. I think I've covered the technical bases, but I'm nog feeling satisfied with the fact what this project adds to the project.

In short: We now can make a complete Digital Twin of our machines, where we can use the data to detect mechanical issues and can monitor trends and thresholds, that can be used for presenting OEE data on a dashboard but also can act with predictive maintenance when we detect that procedures take more time than before.

Kind Regards,

ing Koen Oosterwijk
SOFTWARE ENGINEER

PHONE
+31 (0)88 1152000
DEMCON
INDUSTRIAL SYSTEMS

WEBSITE
www.demcon.com/industrial<http://www.demcon.com/industrial>
[Facebook2klein-Demcon]<https://www.facebook.com/theDEMCONgroup>
[Linkedin2klein-Demcon]<https://www.linkedin.com/company/demcon-industrial-systems>
[Twitter2klein-Demcon]<https://twitter.com/DEMCON>
[Instagram2klein-Demcon]<https://www.instagram.com/demcon_nl/?hl=nl>
Institutenweg 25
7521 PH Enschede
The Netherlands


[Logo-Demcon-handtekening-1]

[Pay-off-e-mailhandtekening]
The content of this communication and any attachments are of a confidential nature and accordingly intended only to be read by the addressee. If anyone receives this communication who is not the addressee and is not authorised by the addressee to receive such communication then such person is requested to notify the sender immediately. Any use of the content of this communication or any attachments by anyone other than the addressee constitutes an unlawful act. Please consider the environment before printing this e-mail.
